//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaData
    {
        public int Id { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public int pizzaTypeId { get; set; }
    }
}
