SET IDENTITY_INSERT [dbo].[CarMakes] ON
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (1, N'Alfa Romeo')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (2, N'Alpina')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (4, N'Audi')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (5, N'Bentley')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (6, N'BMW')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (7, N'Citroen')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (8, N'Dacia')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (9, N'DS')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (10, N'Ferrari')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (11, N'Fiat')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (12, N'Ford')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (13, N'Honda')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (14, N'Hyundai')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (15, N'Infiniti')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (16, N'Jaguar')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (17, N'Jeep')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (18, N'Kia')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (19, N'Lamborghini')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (20, N'Land Rover')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (21, N'Lexus')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (22, N'Lotus')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (23, N'Maserati')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (24, N'Mazda')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (25, N'McLaren')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (26, N'Mercedes')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (27, N'MG')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (28, N'Mini')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (29, N'Mitsubishi')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (30, N'Nissan')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (31, N'Peugeot')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (32, N'Porsche')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (33, N'Renault')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (34, N'Rolls-Royce')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (35, N'Seat')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (36, N'Skoda')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (37, N'Smart')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (38, N'SsangYong')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (39, N'Subaru')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (40, N'Suzuki')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (41, N'Tesla')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (42, N'Toyota')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (43, N'Vauxhall')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (44, N'Volkswagen')
INSERT INTO [dbo].[CarMakes] ([ID], [Name]) VALUES (45, N'Volvo')
SET IDENTITY_INSERT [dbo].[CarMakes] OFF
